/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ConvivialMenu extends javax.swing.JFrame {
    private ArrayList<Pessoa> listaPessoas = new ArrayList<>();
    private ArrayList<Local> listaLocais = new ArrayList<>();
    private final String nome;

    /**
     * Apresenta as opções que podem ser acedidas para configurar a sua inscrição no convívio.
     * 
     * @param listaPessoas lista de pessoas presentes na base de dados.
     * @param listaLocais lista de locais presentes na base de dados.
     * @param nome nome da pessoa cuja conta está ligada.
     */
    public ConvivialMenu(ArrayList<Pessoa> listaPessoas,ArrayList<Local> listaLocais,String nome) {
        this.listaPessoas = listaPessoas;
        this.listaLocais = listaLocais;
        this.nome = nome;
        initComponents();
        nomeContaLabel.setText(nome+"!");
    }
    
    private boolean verificaInscritos(){
        int pessoasInscritas = 0;
        for(int i=0;i<listaLocais.size();i++){
            pessoasInscritas += listaLocais.get(i).getListaInscritos().size();
        }
        
        return pessoasInscritas>0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subtituloLabel = new javax.swing.JLabel();
        apresentarLocaisButton = new javax.swing.JButton();
        selecionarLocaisButton = new javax.swing.JButton();
        seriarLocaisButton = new javax.swing.JButton();
        guestButton = new javax.swing.JButton();
        receitaButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        nomeContaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Convívio");
        setResizable(false);

        subtituloLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtituloLabel.setText("Bem-Vindo ao Menu do Convívio");

        apresentarLocaisButton.setText("Apresentar locais a visitar");
        apresentarLocaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apresentarLocaisButtonActionPerformed(evt);
            }
        });

        selecionarLocaisButton.setText("Selecionar os locais a visitar");
        selecionarLocaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarLocaisButtonActionPerformed(evt);
            }
        });

        seriarLocaisButton.setText("Seriar os locais a visitar");
        seriarLocaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriarLocaisButtonActionPerformed(evt);
            }
        });

        guestButton.setText("Apresentar \"Guest Lists\"");
        guestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestButtonActionPerformed(evt);
            }
        });

        receitaButton.setText("Contabilizar a receita mínima");
        receitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Terminar Sessão");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        nomeContaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subtituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeContaLabel)
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addComponent(apresentarLocaisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selecionarLocaisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seriarLocaisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receitaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtituloLabel)
                    .addComponent(nomeContaLabel))
                .addGap(18, 18, 18)
                .addComponent(apresentarLocaisButton)
                .addGap(18, 18, 18)
                .addComponent(selecionarLocaisButton)
                .addGap(18, 18, 18)
                .addComponent(seriarLocaisButton)
                .addGap(18, 18, 18)
                .addComponent(guestButton)
                .addGap(18, 18, 18)
                .addComponent(receitaButton)
                .addGap(18, 18, 18)
                .addComponent(sairButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seriarLocaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriarLocaisButtonActionPerformed
        ApresentacaoLocaisSeriados novo = new ApresentacaoLocaisSeriados(listaPessoas,listaLocais,nome);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seriarLocaisButtonActionPerformed

    private void guestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestButtonActionPerformed
        EscolheLocalParaGuest novo = new EscolheLocalParaGuest(listaPessoas,listaLocais,nome);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guestButtonActionPerformed

    private void receitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaButtonActionPerformed

        boolean flag;
        flag = verificaInscritos();
        if(flag){
            Receita novo = new Receita(listaPessoas,listaLocais,nome);
            novo.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Não há pessoas inscritas nos locais!","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_receitaButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem a certeza que a pretende terminar sessão?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(confirmacao == JOptionPane.YES_OPTION){
            this.dispose();
            MainMenu novomenu = new MainMenu(listaPessoas,listaLocais);
            novomenu.setVisible(true);
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void apresentarLocaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apresentarLocaisButtonActionPerformed
        ApresentacaoLocais novo = new ApresentacaoLocais(listaPessoas,listaLocais,nome);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_apresentarLocaisButtonActionPerformed

    private void selecionarLocaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarLocaisButtonActionPerformed
        SelecionarLocais novo = new SelecionarLocais(listaPessoas,listaLocais,nome);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_selecionarLocaisButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apresentarLocaisButton;
    private javax.swing.JButton guestButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeContaLabel;
    private javax.swing.JButton receitaButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton selecionarLocaisButton;
    private javax.swing.JButton seriarLocaisButton;
    private javax.swing.JLabel subtituloLabel;
    // End of variables declaration//GEN-END:variables
}
