/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;

/**
 *
 * @author ASUS
 */
public class LocalOptionMenu extends javax.swing.JFrame {
    ArrayList<Pessoa> listaPessoas = new ArrayList<>();
    ArrayList<Local> listaLocais = new ArrayList<>();

    /**
     * Creates new form LocalOptionMenu
     * @param listaPessoas lista de pessoas presentes na base de dados.
     * @param listaLocais lista de locais presentes na base de dados.
     */
    public LocalOptionMenu(ArrayList<Pessoa> listaPessoas,ArrayList<Local> listaLocais) {
        this.listaPessoas = listaPessoas;
        this.listaLocais = listaLocais;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        novoBarButton = new javax.swing.JButton();
        novaExpoButton = new javax.swing.JButton();
        novaAreaDesportivaButton = new javax.swing.JButton();
        novoJardimButton = new javax.swing.JButton();
        SairButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolha o tipo de local a criar");
        setResizable(false);

        novoBarButton.setText("Bar");
        novoBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBarButtonActionPerformed(evt);
            }
        });

        novaExpoButton.setText("Exposicao");
        novaExpoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaExpoButtonActionPerformed(evt);
            }
        });

        novaAreaDesportivaButton.setText("Área Desportiva");
        novaAreaDesportivaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAreaDesportivaButtonActionPerformed(evt);
            }
        });

        novoJardimButton.setText("Jardim");
        novoJardimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJardimButtonActionPerformed(evt);
            }
        });

        SairButton.setText("Regressar");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoBarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novaExpoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novaAreaDesportivaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(novoJardimButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoBarButton)
                .addGap(18, 18, 18)
                .addComponent(novaExpoButton)
                .addGap(18, 18, 18)
                .addComponent(novaAreaDesportivaButton)
                .addGap(18, 18, 18)
                .addComponent(novoJardimButton)
                .addGap(18, 18, 18)
                .addComponent(SairButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novoJardimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJardimButtonActionPerformed
        NewJardim novo = new NewJardim(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoJardimButtonActionPerformed

    private void novaAreaDesportivaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAreaDesportivaButtonActionPerformed
        NewAreaDesportiva novo = new NewAreaDesportiva(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novaAreaDesportivaButtonActionPerformed

    private void novaExpoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaExpoButtonActionPerformed
        NewExposicao novo = new NewExposicao(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novaExpoButtonActionPerformed

    private void novoBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBarButtonActionPerformed
        NewBar novo = new NewBar(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoBarButtonActionPerformed

    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
        MainMenu novo = new MainMenu(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SairButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SairButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton novaAreaDesportivaButton;
    private javax.swing.JButton novaExpoButton;
    private javax.swing.JButton novoBarButton;
    private javax.swing.JButton novoJardimButton;
    // End of variables declaration//GEN-END:variables
}
