/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;

/**
 *
 * @author ASUS
 */
public class PersonOptionMenu extends javax.swing.JFrame {
    
    ArrayList<Pessoa> listaPessoas = new ArrayList<>();
    ArrayList<Local> listaLocais = new ArrayList<>();

    /**
     * Secção de seleção do tipo de utilizador que é pretendido criar.
     * @param listaPessoas lista de pessoas presentes na base de dados.
     * @param listaLocais lista de locais presentes na base de dados.
     */
    public PersonOptionMenu(ArrayList<Pessoa> listaPessoas,ArrayList<Local> listaLocais) {
        this.listaPessoas = listaPessoas;
        this.listaLocais = listaLocais;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoAlunoButton = new javax.swing.JButton();
        novoFuncionarioButton = new javax.swing.JButton();
        novoProfessorButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolha o tipo do novo indivíduo");
        setResizable(false);

        novoAlunoButton.setText("Aluno");
        novoAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoButtonActionPerformed(evt);
            }
        });

        novoFuncionarioButton.setText("Funcionario");
        novoFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFuncionarioButtonActionPerformed(evt);
            }
        });

        novoProfessorButton.setText("Professor");
        novoProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProfessorButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoAlunoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novoFuncionarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(novoProfessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(novoAlunoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoFuncionarioButton)
                .addGap(11, 11, 11)
                .addComponent(novoProfessorButton)
                .addGap(11, 11, 11)
                .addComponent(sairButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novoAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoButtonActionPerformed
        NewAluno novo = new NewAluno(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoAlunoButtonActionPerformed

    private void novoFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFuncionarioButtonActionPerformed
        NewFuncionario novo = new NewFuncionario(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoFuncionarioButtonActionPerformed

    private void novoProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProfessorButtonActionPerformed
        NewProfessor novo = new NewProfessor(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoProfessorButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        MainMenu novo = new MainMenu(listaPessoas,listaLocais);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton novoAlunoButton;
    private javax.swing.JButton novoFuncionarioButton;
    private javax.swing.JButton novoProfessorButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
